#!/bin/tcsh

set runNumber=$1
set torusPolarity = $2
set solenoidPolarity = $3

echo ">> SETTING ENVIRONMENT"
#setenv COATJAVA $CLARA_HOME/plugins/clas12/

echo ">> VARIABLES FOR DECODER $runNumber $torusPolarity and $solenoidPolarity"
echo ">> FILE input $4 "

echo "EXECUTING COATJAVA EVIO2HIPO"

#try this next

echo "COPYING COAT V 6.3.1"
#cp -r /w/hallb-scifs17exp/clas12/bclary/extras/coatjava-6.3.1 .
#./coatjava-6.3.1/bin/evio2hipo -r $runNumber -t $torusPolarity -s $solenoidPolarity $4 -o decoded.hipo

source /site/12gev_phys/softenv.csh 2.3
source /group/clas12/packages/setup.csh
module avail
module load coatjava/6.3.1
evio2hipo -r $runNumber -t $torusPolarity -s $solenoidPolarity $4 -o decoded.hipo
