#!/bin/tcsh

source /site/12gev_phys/softenv.csh 2.3

source /group/clas12/gemc/environment.csh 4.3.1
set nev = `awk 'BEGIN{nev=0;}{if(NF==10) nev++;}END{print nev}' $1`

echo " > EXECUTING GEMC "
echo " > launching $nev events "
echo " > starting gemc job"

gemc $2 -RUNNO=11 -N=${nev} -USE_GUI=0 -INPUT_GEN_FILE="LUND, $1" -OUTPUT="evio, sim.evio"
echo " > finished gemc "
